import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import { getServerSession } from "next-auth";
import { options } from "@/pages/api/auth/[...nextauth]";
import { ReactNode } from "react";
import "remixicon/fonts/remixicon.css";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader showSpinner={false} color="#2D9596" />
        <Nav user={session?.user} expires={session?.expires as string} />
        <main className="py-2 sm:px-10 px-6 container mx-auto">{children}</main>
      </body>
    </html>
  );
}
